### ISSUE TITLE
Disabling a column should prevent horizontal fills into it

### ISSUE THREAD

**Issue by jgbishop** [DataTables/AutoFill#5]
Suppose I have the following DataTable setup:

    new $.fn.dataTable.AutoFill(myTable, {
      "mode": 'x',
      "columnDefs": [
        { enable: false, targets: [0] }
      ]
    });

Even though column 0 doesn't provide the "drag" icon, I can drag data from other columns into that column. It would be great if `enable: false` could also lock down the column, preventing any data from being copied into it.

**Comment by DataTables** [comment]
This repo contains AutoFill v2 which is as of yet unreleased (while I'm still working documentation for it and other extensions) - AutoFill v2 already addresses this issue.

I should note that v2 is not backwards compatible - it uses a new API and new initialisation options.

As this is fixed in the latest version (albeit as of yet unreleased) I'm going to close this issue. v1 is no longer going to see any development or bug fixes from myself (although pull requests are welcome if you need it in v1).
